// src/components/ArchitectureMatrix.vue
<template>
  <div class="architecture-matrix">
    <div class="architecture-tabs" role="tablist" aria-label="Deployment boundaries">
      <button v-for="layer in layers" :key="layer.name" type="button" role="tab" :aria-selected="active === layer.name" :class="{ active: active === layer.name }" @click="active = layer.name">{{ layer.name }}</button>
    </div>
    <div class="architecture-detail"><span>{{ selected.name }}</span><strong>{{ selected.role }}</strong><p>{{ selected.focus }}</p></div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';

const layers = [
  { name: 'Node.js', role: 'Service runtime', focus: 'APIs, workers, and integration boundaries' },
  { name: 'Vite', role: 'Build system', focus: 'Fast feedback and optimized asset delivery' },
  { name: 'Cloudflare', role: 'Edge platform', focus: 'Secure delivery, DNS, and globally distributed runtime' },
  { name: 'Rust', role: 'Systems service', focus: 'Explicit memory safety and predictable performance' },
  { name: 'Go', role: 'Network service', focus: 'Concurrent APIs with a small operational footprint' },
  { name: 'Ruby', role: 'Product service', focus: 'Fast iteration for business workflows and APIs' },
  { name: 'Solidity', role: 'Contract surface', focus: 'Auditable on-chain logic and security research' }
];
const active = ref(layers[0].name);
const selected = computed(() => layers.find((layer) => layer.name === active.value) ?? layers[0]);
</script>

// src/components/ArchitectureMatrix.tsx
import { useState } from 'react';

const layers = [
	['Astro', 'Public shell', 'SEO, content, routing'],
	['React', 'Product UI', 'Complex client state'],
	['Vue', 'Data surfaces', 'Composable dashboards'],
	['Solid', 'Live systems', 'Low-overhead interactions'],
	['Svelte', 'Motion layer', 'Focused visual effects'],
	['Next.js', 'Application lab', 'Server-rendered React products'],
	['Nuxt', 'Application lab', 'Composable Vue products'],
	['Rust', 'Backend service', 'Fast, explicit systems programming'],
	['Go', 'Backend service', 'Small, concurrent network services'],
	['Ruby', 'Backend service', 'Readable product and automation APIs']
	,['Solidity', 'Smart contracts', 'Auditable on-chain security surfaces']
];

export default function ArchitectureMatrix() {
	const [active, setActive] = useState(0);
	const layer = layers[active];

	return (
		<div className="architecture-matrix">
			<div className="architecture-tabs" role="tablist" aria-label="Framework layers">
				{layers.map(([name], index) => (
					<button type="button" role="tab" aria-selected={active === index} className={active === index ? 'active' : ''} onClick={() => setActive(index)}>{name}</button>
				))}
			</div>
			<div className="architecture-detail"><span>{layer[0]}</span><strong>{layer[1]}</strong><p>{layer[2]}</p></div>
		</div>
	);
}
